version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-energy_forecast_db}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-energy_forecast_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Service for Celery
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API Service (FastAPI)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api_server.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_BROKER_URL=${REDIS_BROKER_URL}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Celery Worker Service
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_worker.celery_app worker -l info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_BROKER_URL=${REDIS_BROKER_URL}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  # One-off service to initialize the database
  db-init:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        echo 'Waiting for database to be ready...' &&
        alembic upgrade head &&
        echo 'Database is up to date.'
      "
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PGPASSWORD=${POSTGRES_PASSWORD:-password} # psql command needs this
    depends_on:
      db:
        condition: service_healthy

  # Frontend Service (React + Nginx)
  frontend:
    build:
      context: ./admin_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api
      - db-init # Make frontend wait for db init to complete

  # Development-only service to run npm commands and the Vite dev server
  frontend-dev:
    build:
      context: ./admin_frontend
      dockerfile: Dockerfile.dev
    command: npm run dev # Run the development server
    ports:
      - "5174:5173" # Expose the dev server on host port 5174
    volumes:
      - ./admin_frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
    driver: local
