version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-energy_forecast_db}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-energy_forecast_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Redis Service for Celery
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # MinIO S3-Compatible Storage Service
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - app-network

  # Backend API Service (FastAPI)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api_server.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_BROKER_URL=${REDIS_BROKER_URL}
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY_ID=${MINIO_ROOT_USER:-minioadmin}
      - S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - app-network

  # Celery Worker Service
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_worker.celery_app worker -l info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_BROKER_URL=${REDIS_BROKER_URL}
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY_ID=${MINIO_ROOT_USER:-minioadmin}
      - S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - app-network

  # One-off service to initialize the database
  db-init:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        echo 'Waiting for database to be ready...' &&
        alembic upgrade head &&
        echo 'Database is up to date.'
      "
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PGPASSWORD=${POSTGRES_PASSWORD:-password} # psql command needs this
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # Frontend Service (React + Nginx)
  frontend:
    build:
      context: ./admin_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api
      - db-init # Make frontend wait for db init to complete
    networks:
      - app-network

  # Development-only service to run npm commands and the Vite dev server
  frontend-dev:
    build:
      context: ./admin_frontend
      dockerfile: Dockerfile.dev
    command: npm run dev # Run the development server
    ports:
      - "5174:5173" # Expose the dev server on host port 5174
    volumes:
      - ./admin_frontend:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
