"""Add status and S3 paths to Model table

Revision ID: 2fb253a77cdb
Revises: 79108569c0f0
Create Date: 2025-07-07 03:30:16.936503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb253a77cdb'
down_revision: Union[str, None] = '79108569c0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('status', sa.String(length=50), nullable=False, server_default='PENDING', comment='训练状态: PENDING, TRAINING, COMPLETED, FAILED'))
    op.add_column('models', sa.Column('training_data_path', sa.Text(), nullable=True, comment='训练数据在S3中的路径 (key)'))
    op.alter_column('models', 'model_path',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='主模型文件在S3中的路径 (key)',
               existing_comment='主模型文件的路径')
    op.alter_column('models', 'scaler_path',
               existing_type=sa.TEXT(),
               comment='值缩放器文件在S3中的路径 (key)',
               existing_comment='值缩放器文件的路径',
               existing_nullable=True)
    op.alter_column('models', 'scaler_cov_path',
               existing_type=sa.TEXT(),
               comment='协变量缩放器文件在S3中的路径 (key)',
               existing_comment='协变量缩放器文件的路径',
               existing_nullable=True)
    op.drop_constraint('models_model_version_key', 'models', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('models_model_version_key', 'models', ['model_version'])
    op.alter_column('models', 'scaler_cov_path',
               existing_type=sa.TEXT(),
               comment='协变量缩放器文件的路径',
               existing_comment='协变量缩放器文件在S3中的路径 (key)',
               existing_nullable=True)
    op.alter_column('models', 'scaler_path',
               existing_type=sa.TEXT(),
               comment='值缩放器文件的路径',
               existing_comment='值缩放器文件在S3中的路径 (key)',
               existing_nullable=True)
    op.alter_column('models', 'model_path',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='主模型文件的路径',
               existing_comment='主模型文件在S3中的路径 (key)')
    op.drop_column('models', 'training_data_path')
    op.drop_column('models', 'status')
    # ### end Alembic commands ###
