"""Add detector_path to models table

Revision ID: 3de837a80144
Revises: ee429d7929d6
Create Date: 2025-07-07 12:13:37.431470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de837a80144'
down_revision: Union[str, None] = 'ee429d7929d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('detector_path', sa.Text(), nullable=True, comment='异常检测器文件在S3中的路径 (key)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'detector_path')
    # ### end Alembic commands ###
