import os
import sys
import uuid
import bcrypt
from sqlalchemy import create_engine
from sqlalchemy.orm import Session
from sqlalchemy.exc import OperationalError
from datetime import datetime, timezone
from dotenv import load_dotenv

# Add project root to the Python path to find the database module
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.append(PROJECT_ROOT)

# We import ApiKey just for the class definition, not for the engine
from database.database import ApiKey

def create_standalone_api_key():
    """
    Creates an initial API key in a completely standalone manner.
    It creates its own database engine to avoid any caching issues.
    """
    print("--- Standalone Initial API Key Generation ---")

    # 1. Load environment and create a dedicated engine
    load_dotenv()
    DATABASE_URL = os.getenv("DATABASE_URL")
    if not DATABASE_URL:
        print("[FATAL ERROR] DATABASE_URL environment variable is not set.")
        print("Please ensure your .env file is configured correctly.")
        sys.exit(1)

    try:
        engine = create_engine(DATABASE_URL)
    except Exception as e:
        print(f"[FATAL ERROR] Failed to create SQLAlchemy engine: {e}")
        sys.exit(1)

    # 2. Generate and hash the key
    new_key_str = str(uuid.uuid4())
    print("Generated new key string (this will NOT be stored).")
    hashed_key = bcrypt.hashpw(new_key_str.encode('utf-8'), bcrypt.gensalt())
    key_hash = hashed_key.decode('utf-8')
    print("Key has been successfully hashed using bcrypt.")

    # 3. Create the ORM object, ensuring all NOT NULL fields are set
    new_api_key = ApiKey(
        key_hash=key_hash,
        description="Initial admin key generated by standalone script.",
        is_active=True,
        created_at=datetime.now(timezone.utc)
    )

    # 4. Connect to DB and save the key
    try:
        with Session(engine) as session:
            session.add(new_api_key)
            session.commit()
            print("Successfully saved hashed key to the database.")
    except OperationalError as e:
        print("\n[ERROR] Could not connect to the database.")
        print(f"  - Please ensure the database service is running and accessible at: {DATABASE_URL}")
        print(f"  - Original error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\n[ERROR] An unexpected error occurred while saving the key: {e}")
        sys.exit(1)
    finally:
        # Dispose of the engine to close all connections
        engine.dispose()

    # 5. Print the key for the admin to copy
    print("\n" + "*"*60)
    print("IMPORTANT: This is the ONLY time the API key will be shown.")
    print("Copy it and store it in a safe place.")
    print("\nAPI Key: ")
    print(f"    {new_key_str}")
    print("\n" + "*"*60)
    print("\nScript finished.")

if __name__ == "__main__":
    create_standalone_api_key()